# Generated by Django 5.1.6 on 2025-02-14 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_sid', models.CharField(max_length=100, unique=True)),
                ('caller_number', models.CharField(max_length=20)),
                ('location', models.TextField()),
                ('emergency_type', models.CharField(choices=[('POLICE', 'Police'), ('MEDICAL', 'Medical')], max_length=50)),
                ('incident_number', models.CharField(max_length=50, unique=True)),
                ('priority_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CallInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaker', models.CharField(choices=[('CALLER', 'Caller'), ('SYSTEM', 'System')], max_length=20)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='calls.call')),
            ],
        ),
    ]
