# Generated by Django 5.1.6 on 2025-02-17 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='call',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.AddField(
            model_name='call',
            name='category',
            field=models.CharField(default='GENERAL', max_length=50),
        ),
        migrations.AddField(
            model_name='call',
            name='duration_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='call',
            name='escalated_to_911',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='call',
            name='units_dispatched',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='call',
            name='priority_level',
            field=models.CharField(choices=[('STANDARD', 'Standard'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=20),
        ),
        migrations.AlterField(
            model_name='call',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('DISPATCHED', 'Dispatched'), ('ESCALATED', 'Escalated'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='callinteraction',
            name='speaker',
            field=models.CharField(choices=[('CALLER', 'Caller'), ('DISPATCHER', 'Dispatcher')], max_length=20),
        ),
    ]
