# Generated by Django 5.1.6 on 2025-03-26 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0003_alter_call_category_alter_call_emergency_type_and_more'),
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='assigned_units',
            field=models.ManyToManyField(blank=True, related_name='calls', to='units.unit'),
        ),
    ]
