# Generated by Django 5.1.6 on 2025-03-26 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0004_call_assigned_units'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callinteraction',
            name='call',
        ),
        migrations.RemoveField(
            model_name='call',
            name='assigned_units',
        ),
        migrations.RemoveField(
            model_name='call',
            name='category',
        ),
        migrations.RemoveField(
            model_name='call',
            name='emergency_type',
        ),
        migrations.RemoveField(
            model_name='call',
            name='escalated_to_911',
        ),
        migrations.RemoveField(
            model_name='call',
            name='incident_number',
        ),
        migrations.RemoveField(
            model_name='call',
            name='location',
        ),
        migrations.RemoveField(
            model_name='call',
            name='priority_level',
        ),
        migrations.RemoveField(
            model_name='call',
            name='status',
        ),
        migrations.RemoveField(
            model_name='call',
            name='units_dispatched',
        ),
    ]
