# Generated by Django 5.1.6 on 2025-03-26 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0006_call_incident_delete_callinteraction'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='call_id',
            field=models.CharField(max_length=100, editable=False, null=True, blank=True)
        ),
    ]
