# Generated by Django 5.1.6 on 2025-03-26 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0007_call_call_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='call_id',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True),
        ),
    ]
