# Generated by Django 5.1.6 on 2025-03-26 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrafficStop',
        ),
    ]
