# Generated by Django 5.1.6 on 2025-03-27 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_delete_trafficstop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverslicense',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drivers_licenses', to='records.subject'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='drivers_license',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='records.driverslicense'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='home_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_residents', to='records.address'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='work_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='records.address'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='records.address'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='owner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='records.subject'),
        ),
    ]
