# Generated by Django 5.1.6 on 2025-03-26 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('title', models.CharField(default='Untitled Incident', max_length=100)),
                ('emergency_type', models.CharField(blank=True, choices=[('POLICE', 'Police'), ('MEDICAL', 'Medical')], max_length=50, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('ACTIVE', 'Active'), ('RESOLVED', 'Resolved'), ('ESCALATED', 'Escalated'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=20)),
                ('priority_level', models.CharField(blank=True, choices=[('STANDARD', 'Standard'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_units', models.ManyToManyField(blank=True, related_name='incidents', to='units.unit')),
            ],
        ),
    ]
