# Generated by Django 5.1.6 on 2025-03-26 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0006_call_incident_delete_callinteraction'),
        ('incidents', '0001_initial'),
        ('records', '0002_delete_trafficstop'),
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficStop',
            fields=[
                ('incident_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='incidents.incident')),
                ('reason', models.TextField()),
                ('outcome', models.TextField()),
                ('citation_issued', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('call', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='calls.call')),
                ('officer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='units.unit')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='records.subject')),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='records.vehicle')),
            ],
            bases=('incidents.incident',),
        ),
    ]
